# Generated by Django 2.2.7 on 2019-12-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=60)),
                ('user_pwd', models.CharField(max_length=36)),
                ('user_hp', models.CharField(max_length=20)),
                ('user_level', models.PositiveSmallIntegerField(default=1, null=True)),
                ('is_use', models.CharField(default='Y', max_length=1, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('lastup_time', models.DateTimeField(auto_now=True)),
                ('leave_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('rm_nm', models.CharField(max_length=50)),
                ('post_email', models.CharField(max_length=50)),
                ('get_email', models.CharField(max_length=50)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'noti',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('rm_no', models.IntegerField()),
                ('user_id', models.CharField(max_length=255)),
                ('chk_in_time', models.CharField(max_length=50)),
                ('chk_out_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('seq_no', models.AutoField(primary_key=True, serialize=False)),
                ('rm_nm', models.CharField(max_length=50)),
                ('rm_addr', models.CharField(max_length=255)),
                ('rm_type', models.CharField(max_length=20)),
                ('rm_child', models.IntegerField(null=True)),
                ('rm_adult', models.IntegerField(null=True)),
                ('rm_sun_max_pay', models.CharField(max_length=50, null=True)),
                ('rm_mon_max_pay', models.CharField(max_length=50, null=True)),
                ('rm_max_day', models.CharField(max_length=50, null=True)),
                ('rm_chk_in_time', models.CharField(max_length=20)),
                ('rm_chk_out_time', models.CharField(max_length=20, null=True)),
                ('rm_room1_path', models.CharField(max_length=255, null=True)),
                ('rm_room2_path', models.CharField(max_length=255, null=True)),
                ('rm_room3_path', models.CharField(max_length=255, null=True)),
                ('rm_cik_path', models.CharField(max_length=255, null=True)),
                ('rm_living_path', models.CharField(max_length=255, null=True)),
                ('rm_tol1_path', models.CharField(max_length=255, null=True)),
                ('rm_tol2_path', models.CharField(max_length=255, null=True)),
                ('rm_is_use', models.CharField(default='Y', max_length=1, null=True)),
                ('rm_max_pay', models.CharField(max_length=50, null=True)),
                ('rm_email', models.CharField(max_length=60, null=True)),
                ('rm_phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
